import { Product } from "@/types/types";

export const reorderList: Product[] = [
  {
    id: 1,
    title: "Sony WH-1000XM5 Wireless Headphones",
    description: "Industry-leading noise-canceling headphones with 30-hour battery life.",
    price: 399.99,
    discountPercentage: 15,
    rating: 4.7,
    stock: 50,
    brand: "Sony",
    category: "Electronics",
    thumbnail: "https://m.media-amazon.com/images/I/81XwHbHqtoL._AC_SL1500_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/81XwHbHqtoL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71Zo3rId4LL._AC_SL1500_.jpg",
    ],
    slug: "sony-wh-1000xm5",
  },
  {
    id: 2,
    title: "Apple MacBook Pro 16-inch (2023)",
    description: "Powerful laptop with M2 Pro chip for unmatched performance.",
    price: 2499.99,
    discountPercentage: 10,
    rating: 4.9,
    stock: 20,
    brand: "Apple",
    category: "Computers",
    thumbnail: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp16-spacegray-gallery1-202301?wid=400&hei=400&fmt=jpeg&qlt=95&.v=1671304677530",
    images: [
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp16-spacegray-gallery1-202301?wid=400&hei=400&fmt=jpeg&qlt=95&.v=1671304677530",
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp16-spacegray-gallery2-202301?wid=400&hei=400&fmt=jpeg&qlt=95&.v=1671304677843",
    ],
    slug: "apple-macbook-pro-2023",
  },
  {
    id: 3,
    title: "Samsung Galaxy S23 Ultra",
    description: "The ultimate smartphone with an advanced camera and stunning design.",
    price: 1199.99,
    discountPercentage: 5,
    rating: 4.8,
    stock: 100,
    brand: "Samsung",
    category: "Mobile",
    thumbnail: "https://image-us.samsung.com/SamsungUS/smartphones/galaxy-s23-ultra/images/galaxy-s23-ultra_highlights_kv_mo.jpg",
    images: [
      "https://image-us.samsung.com/SamsungUS/smartphones/galaxy-s23-ultra/images/galaxy-s23-ultra_highlights_kv_mo.jpg",
      "https://image-us.samsung.com/SamsungUS/smartphones/galaxy-s23-ultra/images/gallery_01.jpg",
    ],
    slug: "samsung-galaxy-s23-ultra",
  },
  {
    id: 4,
    title: "Dyson V15 Detect Vacuum Cleaner",
    description: "The most powerful and intelligent cordless vacuum with laser technology.",
    price: 749.99,
    discountPercentage: 12,
    rating: 4.6,
    stock: 35,
    brand: "Dyson",
    category: "Home Appliances",
    thumbnail: "https://www.dyson.com/content/dam/dyson/images/products/dyson-v15-detect-vacuum/standard-v15-detect.png",
    images: [
      "https://www.dyson.com/content/dam/dyson/images/products/dyson-v15-detect-vacuum/standard-v15-detect.png",
      "https://www.dyson.com/content/dam/dyson/images/products/dyson-v15-detect-vacuum/alt-images/v15-detect_alt-image-1.jpg",
    ],
    slug: "dyson-v15-detect",
  },
  {
    id: 5,
    title: "Nike Air Max 270 Sneakers",
    description: "Stylish and comfortable sneakers for everyday wear.",
    price: 159.99,
    discountPercentage: 20,
    rating: 4.5,
    stock: 200,
    brand: "Nike",
    category: "Footwear",
    thumbnail: "https://static.nike.com/a/images/t_default/9e1f0d3e-2f04-4a17-96a5-5f66b07b7b23/air-max-270-shoes-KkLcGR.png",
    images: [
      "https://static.nike.com/a/images/t_default/9e1f0d3e-2f04-4a17-96a5-5f66b07b7b23/air-max-270-shoes-KkLcGR.png",
      "https://static.nike.com/a/images/t_default/318478b1-ec2c-437f-8858-2dc891fbbe90/air-max-270-shoes-KkLcGR.png",
    ],
    slug: "nike-air-max-270",
  },
];
